# Generated by Django 4.0 on 2022-02-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_sit',
            new_name='portfolio_site',
        ),
    ]
